// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"
)

const createContact = `-- name: CreateContact :exec
INSERT INTO contacts (name, email, message) VALUES (?, ?, ?)
`

type CreateContactParams struct {
	Name    string `json:"name"`
	Email   string `json:"email"`
	Message string `json:"message"`
}

func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) error {
	_, err := q.db.ExecContext(ctx, createContact, arg.Name, arg.Email, arg.Message)
	return err
}

const getContactByID = `-- name: GetContactByID :one
SELECT id, name, email, message, created_at FROM contacts WHERE id = ?
`

func (q *Queries) GetContactByID(ctx context.Context, id int64) (Contact, error) {
	row := q.db.QueryRowContext(ctx, getContactByID, id)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const listContacts = `-- name: ListContacts :many
SELECT id, name, email, message, created_at FROM contacts
`

func (q *Queries) ListContacts(ctx context.Context) ([]Contact, error) {
	rows, err := q.db.QueryContext(ctx, listContacts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
