// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CreateContact(ctx context.Context, arg CreateContactParams) error
	GetContactByID(ctx context.Context, id int64) (Contact, error)
	ListContacts(ctx context.Context) ([]Contact, error)
}

var _ Querier = (*Queries)(nil)
